### ISSUE TITLE
error

### ISSUE THREAD

**Issue by honglioslo** [sjkelly/SaveREPL.jl#1]
![skjermbilde](https://user-images.githubusercontent.com/16225129/30743925-f960d214-9f9f-11e7-9c9a-adaf115282a9.PNG)

**Comment by carstenbauer** [comment]
I would try to fix this. @sjkelly do you still maintain this package, i.e. should I make a PR? Otherwise I would fork and maintain it in my github. Of course I'd put a reference to give you credit.

**Comment by sjkelly** [comment]
Thanks for the interest in the project. I do not maintain this anymore. A
fork would be best.

**Comment by carstenbauer** [comment]
Please update your README.md stating that this package isn't maintained any longer and add a reference to this repository: https://github.com/crstnbr/SaveREPL.jl.
